out:



err:
ic| in_paths: {'additional_pairs': 'D:\\mine2sirius_pipe\\data\\Test_folder\\OUT\\processed\\processed_iimn_fbmn_edges_msannotation.csv',
               'feature_ms2': 'D:\\mine2sirius_pipe\\data\\Test_folder\\OUT\\processed\\processed_iimn_fbmn.mgf',
               'feature_quantification': 'D:\\mine2sirius_pipe\\data\\Test_folder\\OUT\\processed\\processed_iimn_fbmn_quant.csv',
               'mzmine_log': 'D:\\mine2sirius_pipe\\data\\Test_folder\\OUT\\processed\\mzmine_log.txt',
               'processed_data_paths': ['D:\\mine2sirius_pipe\\data\\Test_folder\\OUT\\processed'],
               'sample_metadata': ['D:\\mine2sirius_pipe\\data\\Test_folder\\OUT\\processed']}
D:\mine2sirius_pipe\rampt\helpers\logging.py:177: UserWarning: [2025-01-31 09:38:20][rampt][WARNING]	Status of None was not marked DONE. The FBMN run was unsuccessful.
  warnings.warn(f"[{get_now()}][{program}][WARNING]\t{message}", *args, **kwargs)
